ALTER SESSION SET CONTAINER=XEPDB1;

CREATE USER sample_user IDENTIFIED BY sample_user;
GRANT CONNECT TO sample_user;
GRANT CREATE SESSION TO sample_user;
GRANT CREATE TABLE TO sample_user;
GRANT CREATE SEQUENCE TO sample_user;
GRANT CREATE TRIGGER TO sample_user;
ALTER USER sample_user QUOTA unlimited ON users;
ALTER USER sample_user IDENTIFIED BY sample_user ACCOUNT UNLOCK;

CREATE TABLE SAMPLE_USER.USERS
(
    ID          NUMBER                NOT NULL,
    NAME        VARCHAR (255 CHAR)    NOT NULL,
    SURNAME     VARCHAR (255 CHAR)    NOT NULL
);

CREATE UNIQUE INDEX SAMPLE_USER.T_USERS_PK ON SAMPLE_USER.USERS
    (ID)
    LOGGING
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE SAMPLE_USER.USERS ADD (CONSTRAINT T_USERS_PK
  PRIMARY KEY
  (ID)
  USING INDEX SAMPLE_USER.T_USERS_PK
  ENABLE VALIDATE);
